# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.23.2"
docker_compose_path: /usr/local/bin/docker-compose

# A list of users who will be added to the docker group.
docker_users: []
