---
all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    domain: example.com
    orderer_type: solo
  children:
    nodes:
      hosts:
        orderer.example.com:
          node_roles:
            - root_orderer
            - orderer
            - peer
            - root_peer
            - explorer
          org: mainorg
          ansible_host: 192.168.33.10
          ansible_user: vagrant
          ansible_private_key_file: /Users/a14846/workspace/src/github.com/nagaa052/sample_ansible/fabric/.vagrant/machines/default/virtualbox/private_key
        # # Same structure for any other nodes
        # one.example.com:
        #   node_roles:
        #     - peer
        #   org: one
        #   ansible_host: 1.2.3.5
        #   ansible_user: ubuntu
        #   ansible_private_key_file: ~/test.pem
        # two.example.com:
        #   node_roles:
        #     - peer
        #   org: two
        #   ansible_host: 1.2.3.6
        #   ansible_user: ubuntu
        #   ansible_private_key_file: ~/test.pem
